### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Beclamide** [passy/angular-masonry#100]
I've just installed the Bower package and I'm getting a TypeError: undefined is not a function error in Chrome when the page loads.

I found that other people have had the error when scripts aren't loaded in the correct order, but I think I'm doing it right.

```html
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="bower_components/jquery-bridget/jquery.bridget.js"></script>
<script src="bower_components/get-style-property/get-style-property.js"></script>
<script src="bower_components/get-size/get-size.js"></script>
<script src="bower_components/eventEmitter/EventEmitter.js"></script>
<script src="bower_components/eventie/eventie.js"></script>
<script src="bower_components/doc-ready/doc-ready.js"></script>
<script src="bower_components/matches-selector/matches-selector.js"></script>
<script src="bower_components/outlayer/item.js"></script>
<script src="bower_components/outlayer/outlayer.js"></script>
<script src="bower_components/masonry/masonry.js"></script>
<script src="bower_components/imagesloaded/imagesloaded.js"></script>
<script src="bower_components/angular-masonry/angular-masonry.js"></script>
```

I've made sure jQuery is 2.1.1 too. Does anyone have any ideas?

**Comment by mikefab** [comment]
Neither adding jquery-bridget  nor adding load-images="false" to <div masonry worked for me.

**Comment by fmpwizard** [comment]
@mikefab I found out the error may have several causes, this library depends on a few other js libraries, but not all the time, so to see which one you are missing, go ahead and use the non min version of the plugin, then on the stack trace you should be able to see which function call is the one being undefined, that should then help track down which library you are missing

**Comment by hankim813** [comment]
@dddaaammmooo thank you, adding the jquery-bridget worked for me.

**Comment by selvait90** [comment]
Hi @passy 

I am also getting the same error when i try to run the example in my local. From the error message, looks like it is not recognising the masonry elements - line no 62 and 100.

*script.js
var app = angular.module("masonryExample", ['wu.masonry']);
....

*index.html
...
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js"></script>
<script src="script.js"></script>
<script src="angular-masonry.js"></script>
...

*Error
 TypeError: undefined is not a function
    at preLink (file:///Users/selva/learn/angularjs/angularjs-examples/instant-search/angular-masonry.js:117:19)
    at i (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:43:396)
    at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:39:307)
    at i (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:43:454)
    at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:39:307)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:38:372
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:16:160
    at Object.e.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:88:347)
    at Object.e.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:88:454)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:16:116 <masonry column-width="200">
7angular.min.js:62 TypeError: undefined is not a function
    at controller.appendBrick (file:///Users/selva/learn/angularjs/angularjs-examples/instant-search/angular-masonry.js:78:19)
    at preLink (file:///Users/selva/learn/angularjs/angularjs-examples/instant-search/angular-masonry.js:145:16)
    at i (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:43:396)
    at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:39:307)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:38:372
    at Object.<anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:148:122)
    at Object.e.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:86:286)
    at Object.e.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:88:506)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:16:116
    at Object.d [as invoke] (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js:27:308) <div class="masonry-brick ng-scope" ng-repeat="brick in items">

**Comment by passy** [comment]
@selvait90 Could you check which lines this refers to in your installation? There's most certainly a missing dependency somewhere. :)

**Comment by selvait90** [comment]
thanks a lot @passy I was able to resolve the error by adding dependencies in following order.

src="jquery-1.11.2.min.js"    
src="masonry.pkgd.min.js" 
src="imagesloaded.pkgd.min.js"
src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js"
src="angular-masonry.js"
src="myApp.js"

But I am developing the application in pure javascript without jQuery, So Is there way to get rid of the jQuery dependency in masonry plugin?

**Comment by ozasadnyy** [comment]
I have the same question as @selvait90 . Can I use masonry without jquery? Because the documentation said that I can, but actually I got next errors:
```
 TypeError: undefined is not a function
    at link.pre (http://localhost:8080/app/js/scripts.js:11952:29)
    at invokeLinkFn (http://localhost:8080/app/js/scripts.js:3492:21)
    at nodeLinkFn (http://localhost:8080/app/js/scripts.js:3270:21)
    at compositeLinkFn (http://localhost:8080/app/js/scripts.js:3108:21)
    at compositeLinkFn (http://localhost:8080/app/js/scripts.js:3108:119)
    at compositeLinkFn (http://localhost:8080/app/js/scripts.js:3108:119)
    at $get.node (http://localhost:8080/app/js/scripts.js:3089:40)
    at link (http://localhost:8080/app/js/scripts.js:8056:17)
    at invokeLinkFn (http://localhost:8080/app/js/scripts.js:3492:21)
    at nodeLinkFn (http://localhost:8080/app/js/scripts.js:3274:87) <div masonry="{ 'isFitWidth': true }" class="masonry">

TypeError: undefined is not a function
    at appendBrick (http://localhost:8080/app/js/scripts.js:11931:119)
    at link.pre (http://localhost:8080/app/js/scripts.js:11974:26)
    at invokeLinkFn (http://localhost:8080/app/js/scripts.js:3492:21)
    at nodeLinkFn (http://localhost:8080/app/js/scripts.js:3270:21)
    at compositeLinkFn (http://localhost:8080/app/js/scripts.js:3108:21)
    at $get.node (http://localhost:8080/app/js/scripts.js:3089:40)
    at $get.boundTranscludeFn (http://localhost:8080/app/js/scripts.js:3121:59)
    at controllersBoundTransclude (http://localhost:8080/app/js/scripts.js:3212:25)
    at http://localhost:8080/app/js/scripts.js:7332:32
    at Object.$watchCollectionAction [as fn] (http://localhost:8080/app/js/scripts.js:4718:92) <div class="masonry-brick md-whiteframe-z1 ng-scope" ng-repeat="pictureThumbnail in pictureThumbnails">
```

**Comment by 2013gang** [comment]
Latest masonry already goes without jQuery. I totally think angular-masonry should remove jQuery depedency too.

I think @passy already had a feature quest for removing jqeury dependency.

**Comment by pwlarry** [comment]
I'm still getting this issue. Dependencies set up in the right order (referring to previous posts). I am using browserify to bundle all JS, could that be causing an issue?

var $ = require('jquery');
require('angular');
require('angular-ui-router');
require('jquery-ui');
require('angular-sanitize');
require('angular-module-animate');
require('jquery-bridget');
require('masonry-layout');
require('imagesloaded');
require('../../bower_components/angular-masonry/angular-masonry');

Error I'm getting:

TypeError: undefined is not a function
    at preLink (http://localhost/test/public/build/js/bundle.js:118:19)
    at nodeLinkFn (http://localhost/test/public/build/js/bundle.js:12832:13)
    at compositeLinkFn (http://localhost/test/public/build/js/bundle.js:12246:13)
    at publicLinkFn (http://localhost/test/public/build/js/bundle.js:12142:30)
    at compile (http://localhost/test/public/build/js/bundle.js:5819:9)
    at nodeLinkFn (http://localhost/test/public/build/js/bundle.js:12852:13)
    at compositeLinkFn (http://localhost/test/public/build/js/bundle.js:12246:13)
    at publicLinkFn (http://localhost/test/public/build/js/bundle.js:12142:30)
    at updateView (http://localhost/test/public/build/js/bundle.js:5757:23)
    at http://localhost/test/public/build/js/bundle.js:5719:11 <section id="page-home" class="page_home ng-scope" masonry="" load-images="false">

**Comment by prkr88** [comment]
Fixed by including imagesloaded!

**Comment by ykhrustalev** [comment]
+1 for missing jquery-bridget

**Comment by jjwsteele** [comment]
adding jquery-bridget worked for me as well

**Comment by iDuuck** [comment]
I think the problem for the people without the fix (adding jquery-bridget) is simply requiring jquery-bridget **before** requiring the first masonry dependency. I had the problem that I was working with bower and the dependencies were required **before** jquery-bridget. Moving jquery-bridget to the top fixed the problem.

**Comment by kentbong** [comment]
any latest solution for this problem? I still facing the same problem, after added with jquery-bridget.js and also include the (load-images="false" to <div masonry>). Still having with "undefined" problem. Much appreciated if anyone can help. Thanks.

**Comment by clov3rly** [comment]
I think it might be helpful for some (like me :P) to be a bit more explicit about including the dependencies in the html/js build. 

I do now see that step 3 under #Usage in the readme is "Include dependencies in your HTML." but I came to the plugin through the homepage first, which doesn't make any mention of it. So I was confused for a bit there.

What worked for me was including [masonry](http://cdnjs.cloudflare.com/ajax/libs/masonry/3.2.2/masonry.pkgd.js) and [imagesloaded](http://imagesloaded.desandro.com/imagesloaded.pkgd.js) in my build system (after jQuery, before angular, not sure if it matters).

I didn't (at least as of yet) need to install jquery-bridget...

**Comment by fourmisz** [comment]
Hi. I have fixed this problem. 

First, I manually downloaded [jquery-bridget] [imagesloaded] from bower.
Second, I checked depedencies.
Finally,

<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="bower_components/jquery-bridget/jquery.bridget.js"></script>
<script src="bower_components/masonry/dist/masonry.pkgd.js"></script>
<script src="bower_components/imagesloaded/imagesloaded.pkgd.js"></script>
<script src="bower_components/angular/angular.js"></script>
<script src="bower_components/angular-route/angular-route.js"></script>
<script src="bower_components/angular-resource/angular-resource.js"></script>
<script src="bower_components/angular-cookies/angular-cookies.js"></script>
<script src="bower_components/angular-masonry/angular-masonry.js"></script>

I loaded js files like this and error disappeared.

**Comment by leads** [comment]
Moving jquery-bridget up to the top of the bower dependencies list sorted it for me.

**Comment by arsenetoumani** [comment]
@clov3rly's answer worked for me. Including mansory before angular.

**Comment by gimox** [comment]
it's a broserify problem, it load dependency ordered as bower.json file, add first jquery and jquery-bridge and work.

**Comment by kentbong** [comment]
Hi all, I sorted it by placing my script as below order: 

  <script src="lib/jquery.js"></script>
  <script src="lib/jquery.bridget.js"></script>
  <script src="lib/angular.js"></script>
  <script src="lib/angular-route.js"></script>
  <script src="lib/firebase.js"></script>
  <script src="lib/angularfire.min.js"></script>
  <script src="lib/bootstrap.js"></script>
  <script src="lib/ui-bootstrap-tpls-0.12.1.js"></script>
  <script src="lib/masonry.pkgd.min.js"></script>
  <script src="lib/imagesloaded.pkgd.js"></script>
  <script src="lib/angular-masonry.js"></script>

But, I have a problem now, sometimes the pictures is loaded as 1 single column(vertically), sometimes it was fine. Any idea? Thanks.

**Comment by iDuuck** [comment]
@kentbong I think we need some more insights into this, because we need to reproduce the error somehow.

**Comment by mayankdixit** [comment]
here is a fiddle that trhows this error: @passy 
http://jsfiddle.net/c8dn82vp/

**Comment by koshuang** [comment]
I also have this problem, it works when I add jquery-bridget to bower.js and make it before angular-mansory.
```
    "jquery-bridget": "~1.1.0",
    "angular-masonry": "~0.8.1",
```

**Comment by cabilluos** [comment]
Hi I have the same problem that @kentbong reported.

**Comment by passy** [comment]
Sorry, but this is impossible to look at for individual cases. It's always the loading order and there are plenty examples that have the correct one and I'd recommend to not do this manually at all and rely on some module loader or tools like [wiredep](https://github.com/stephenplusplus/wiredep) to deal with it.

**Comment by alexislg2** [comment]
Hey.
Why is this issue closed? I tries to include manually all the dependencies (imageloaded, jquery, jquery-bridget...) and try all different orders but still get the same error.
By the way, the demo URL does not work anymore so I really think there is a bug
http://www.directiv.es/angular-masonry
Could you please re open?

**Comment by OverlappingElvis** [comment]
Solved by uninstalling angular-masonry, then installing jquery-bridget before reinstalling angular-masonry. This should be fixed in angular-masonry's bower dependencies...

**Comment by azharkhan** [comment]
despite all of the above solutions or workarounds, this is still an issue. 

i've tried changing the order of the dependencies (they get automagically injected in my index.html), installing jquery-bridget etc. but I can't seem to get past `$element.masonry` is not a function.

**Comment by twrk** [comment]
+1 to @OverlappingElvis' fix, thanks!!

**Comment by lidiexy** [comment]
+1 to @OverlappingElvis

**Comment by stuartm** [comment]
These dependencies should be listed on the home page.

**Comment by popovevgeny** [comment]
Hey
Just got the same issue.

Reordering dependancies in bower.json solved my problem:

	"dependencies": {
    	"jquery": "~2.1.0",
    	"jquery-bridget": "~1.1.0",
    	"angular": "~1.3.0",
    	"masonry": "~3.2.0",
    	"imagesloaded": "~3.1.0"
 	}

**Comment by Shingaz** [comment]
Totally agree with @stuartm. I use wiredep as @passy mentioned but actually the dependancies are removed then reinjected each time I build so the order of dependencies in bower.js matters. And it shouldn't =)

**Comment by mreigen** [comment]
@fourmisz +1

**Comment by RopoMen** [comment]
Issue is in this library.
Yes, masonry currently has "no jQuery" support and I'm not using jQuery in my AnguarJS application atm.
BUT
Issue is in this [line](https://github.com/passy/angular-masonry/blob/master/src/angular-masonry.js#L133) in angular-masonry.js. That may be issue in all other element.masonry() referencies as well. Like current masonry [readme](https://github.com/desandro/masonry) says masonry can be initialized like this without jQuery
```js
// vanilla JS
var grid = document.querySelector('.grid');
var msnry = new Masonry( grid, {
  // options...
  itemSelector: '.grid-item',
  columnWidth: 200
});
```

**Comment by AlexLai1990** [comment]
I have the same issue with the current demo now. I agree with @RopoMen. Is there anyway to solve for current version?

**Comment by ykwx** [comment]
I was including all of the correct dependencies in the correct order as mentioned above in the documentation. However, I was referencing them after my main vendor.js that gulp creates – so it was making one big js file with everything in an undefined order. 

I moved the list of dependencies above this block and it works. If you're using gulp maybe check this. 

`        
        
        
        
        `

**Comment by srmolesto** [comment]
@iDuuck your solution worked for me! Moving jquery-bridget to the top fixed the problem ;)

**Comment by mkurshumov** [comment]
+1 adding jquery-bridget fixed the issue
